name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main_test
  workflow_dispatch:
    inputs:
      github_token:
        description: 'A GitHub token for pushing to the repo. Example: https://git.io/passing-token'
        required: true
      branch:
        description: 'Branch name for pushing GitHub pages files'
        required: true
        default: "gh-pages"
      folder:
        description: 'Folder where Doxygen will generate the HTML build files'
        required: true
        default: "docs/html"
      config_file:
        description: 'Path of the Doxygen configuration file'
        required: true
        default: "Doxyfile"
      target_folder:
        description: 'Directory on the deployment branch for pushing the build files'
        required: false
      doxygen_version:
        description: 'Version of Doxygen to install'
        required: false
        default: "1.9.6"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: "true"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget graphviz
      shell: bash

    - name: Install Doxygen v${{ github.event.inputs.doxygen_version }}
      run: |
        transformed_version=$(echo "${{ inputs.doxygen_version }}" | tr '.' '_')
        wget https://github.com/doxygen/doxygen/releases/download/Release_${transformed_version}/doxygen-${{ github.event.inputs.doxygen_version }}.linux.bin.tar.gz
        tar -xzf doxygen-${{ github.event.inputs.doxygen_version }}.linux.bin.tar.gz
        sudo mv doxygen-${{ github.event.inputs.doxygen_version }}/bin/doxygen /usr/local/bin/doxygen
      shell: bash

    - name: Generate Doxygen Documentation
      run: |
        cd doxygen/
        doxygen ${{ github.event.inputs.config_file }}
      shell: bash
      
    - name: Create .nojekyll (ensures pages with underscores work on gh pages)
      run: touch ${{ github.event.inputs.folder }}/.nojekyll
      shell: bash

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ github.event.inputs.github_token }}
        branch: ${{ github.event.inputs.branch }}
        folder: ${{ github.event.inputs.folder }}
        target-folder: ${{ github.event.inputs.target_folder }}
    # steps:
    #   - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       branch: gh-pages
    #       folder: doxygen/
    #       config_file: doxygen/Doxyfile.rpmsglite
    #       doxygen_version: 1.9.6
