name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main_test
  workflow_dispatch:
env:
  doxygen_version: "1.9.6"
  branch: "gh-pages-test"
  directory: "doc"
  target_dir: "."
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: "true"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget graphviz
      shell: bash

    - name: Install Doxygen v${doxygen_version}
      run: |
        transformed_version=$(echo "${doxygen_version}" | tr '.' '_')
        wget https://github.com/doxygen/doxygen/releases/download/Release_${transformed_version}/doxygen-${doxygen_version}.linux.bin.tar.gz
        tar -xzf doxygen-${doxygen_version}.linux.bin.tar.gz
        sudo mv doxygen-${doxygen_version}/bin/doxygen /usr/local/bin/doxygen
      shell: bash

    - name: Generate Doxygen Documentation
      run: |
        cd doxygen/
        doxygen Doxyfile.rpmsglite
      shell: bash
      
    - name: Create .nojekyll (ensures pages with underscores work on gh pages)
      run: touch ${directory}/.nojekyll
      shell: bash

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${branch}
        folder: ${directory}
        target-folder: ${target_folder}
    # steps:
    #   - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       branch: gh-pages
    #       folder: doxygen/
    #       config_file: doxygen/Doxyfile.rpmsglite
    #       doxygen_version: 1.9.6
