on:
  create:

name: Release
permissions:
    contents: write
    id-token: write
jobs:
  release-cross-arch:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
