on:
  push:
    tags:
    - "v*"

name: Release
permissions:
    contents: write
    id-token: write
jobs:
  release-cross-arch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
