name: Deploy Applications
run-name: Deploy Applications - ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Environment to build and publish e.g. sit, dev
        default: dev
        type: choice
        options:
          - dev
          - sit
          - uat
          - prod

jobs:
  release:
    runs-on: ubuntu-latest
    name: Mapping applications - ${{ inputs.environment }}
    # ... job and steps
